/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Usuario
 */
public class CalculadoraView extends javax.swing.JFrame {

    /**
     * Creates new form preCalcuForm
     */
    public CalculadoraView() {
        expreStr = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pantalla = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BotonDelete = new javax.swing.JButton();
        BotonClear = new javax.swing.JButton();
        BotonParentesisAbre = new javax.swing.JButton();
        BotonParentesisCierra = new javax.swing.JButton();
        BotonDividir = new javax.swing.JButton();
        Num7 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        BotonRestar = new javax.swing.JButton();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonPunto = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA QUACK");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText(" ");
        jPanel1.add(jLabel1);

        Pantalla.setBackground(new java.awt.Color(222, 216, 216));
        Pantalla.setColumns(20);
        Pantalla.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaActionPerformed(evt);
            }
        });
        jPanel1.add(Pantalla);
        jPanel1.add(jSeparator1);
        jPanel1.add(jLabel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CALCULADORA RAM");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(5, 4, 3, 3));

        BotonDelete.setBackground(new java.awt.Color(255, 102, 51));
        BotonDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonDelete.setText("DEL");
        BotonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(BotonDelete);

        BotonClear.setBackground(new java.awt.Color(204, 0, 0));
        BotonClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonClear.setText("CA");
        BotonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClearActionPerformed(evt);
            }
        });
        jPanel3.add(BotonClear);

        BotonParentesisAbre.setBackground(new java.awt.Color(0, 204, 51));
        BotonParentesisAbre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonParentesisAbre.setText("(");
        BotonParentesisAbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParentesisAbreActionPerformed(evt);
            }
        });
        jPanel3.add(BotonParentesisAbre);

        BotonParentesisCierra.setBackground(new java.awt.Color(0, 204, 51));
        BotonParentesisCierra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonParentesisCierra.setText(")");
        BotonParentesisCierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParentesisCierraActionPerformed(evt);
            }
        });
        jPanel3.add(BotonParentesisCierra);

        BotonDividir.setBackground(new java.awt.Color(0, 204, 51));
        BotonDividir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonDividir.setText("/");
        BotonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDividirActionPerformed(evt);
            }
        });
        jPanel3.add(BotonDividir);

        Num7.setBackground(new java.awt.Color(35, 35, 35));
        Num7.setForeground(new java.awt.Color(204, 204, 204));
        Num7.setText("7");
        Num7.setBorder(null);
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });
        jPanel3.add(Num7);

        Num8.setBackground(new java.awt.Color(35, 35, 35));
        Num8.setForeground(new java.awt.Color(204, 204, 204));
        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });
        jPanel3.add(Num8);

        Num9.setBackground(new java.awt.Color(35, 35, 35));
        Num9.setForeground(new java.awt.Color(204, 204, 204));
        Num9.setText("9");
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });
        jPanel3.add(Num9);

        BotonMultiplicar.setBackground(new java.awt.Color(0, 204, 51));
        BotonMultiplicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonMultiplicar.setText("*");
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMultiplicar);

        Num4.setBackground(new java.awt.Color(35, 35, 35));
        Num4.setForeground(new java.awt.Color(204, 204, 204));
        Num4.setText("4");
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });
        jPanel3.add(Num4);

        Num5.setBackground(new java.awt.Color(35, 35, 35));
        Num5.setForeground(new java.awt.Color(204, 204, 204));
        Num5.setText("5");
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });
        jPanel3.add(Num5);

        Num6.setBackground(new java.awt.Color(35, 35, 35));
        Num6.setForeground(new java.awt.Color(204, 204, 204));
        Num6.setText("6");
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });
        jPanel3.add(Num6);

        BotonRestar.setBackground(new java.awt.Color(0, 204, 51));
        BotonRestar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonRestar.setText("-");
        BotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarActionPerformed(evt);
            }
        });
        jPanel3.add(BotonRestar);

        Num1.setBackground(new java.awt.Color(35, 35, 35));
        Num1.setForeground(new java.awt.Color(204, 204, 204));
        Num1.setText("1");
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });
        jPanel3.add(Num1);

        Num2.setBackground(new java.awt.Color(35, 35, 35));
        Num2.setForeground(new java.awt.Color(204, 204, 204));
        Num2.setText("2");
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });
        jPanel3.add(Num2);

        Num3.setBackground(new java.awt.Color(35, 35, 35));
        Num3.setForeground(new java.awt.Color(204, 204, 204));
        Num3.setText("3");
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });
        jPanel3.add(Num3);

        BotonSuma.setBackground(new java.awt.Color(0, 204, 51));
        BotonSuma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });
        jPanel3.add(BotonSuma);

        BotonPunto.setBackground(new java.awt.Color(0, 204, 51));
        BotonPunto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonPunto.setText(".");
        BotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPuntoActionPerformed(evt);
            }
        });
        jPanel3.add(BotonPunto);

        Num0.setBackground(new java.awt.Color(35, 35, 35));
        Num0.setForeground(new java.awt.Color(204, 204, 204));
        Num0.setText("0");
        Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num0ActionPerformed(evt);
            }
        });
        jPanel3.add(Num0);

        BotonIgual.setBackground(new java.awt.Color(59, 94, 233));
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        jPanel3.add(BotonIgual);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "+";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
        expreStr = expreStr + "1";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num1ActionPerformed

    private void BotonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClearActionPerformed
        // TODO add your handling code here:
        expreStr = "";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonClearActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "8";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "3";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num3ActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        // TODO add your handling code here:
        pruebaEval(expreStr);
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void BotonParentesisAbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParentesisAbreActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "(";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonParentesisAbreActionPerformed

    private void BotonParentesisCierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParentesisCierraActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + ")";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonParentesisCierraActionPerformed

    private void BotonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDividirActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "/";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonDividirActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "7";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num7ActionPerformed

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "9";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num9ActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicarActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "*";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonMultiplicarActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "4";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "5";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "6";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num6ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "2";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num2ActionPerformed

    private void BotonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestarActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "-";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonRestarActionPerformed

    private void BotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPuntoActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + ".";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonPuntoActionPerformed

    private void Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num0ActionPerformed
        // TODO add your handling code here:
        expreStr = expreStr + "0";
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_Num0ActionPerformed

    private void BotonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeleteActionPerformed
        // TODO add your handling code here:
        int ext = expreStr.length();
        if(ext > 0){
            expreStr = expreStr.substring(0, ext-1);
        }
        Pantalla.setText(expreStr);
    }//GEN-LAST:event_BotonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonClear;
    private javax.swing.JButton BotonDelete;
    private javax.swing.JButton BotonDividir;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonParentesisAbre;
    private javax.swing.JButton BotonParentesisCierra;
    private javax.swing.JButton BotonPunto;
    private javax.swing.JButton BotonRestar;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    //Usuario
    private String expreStr;
    
    public void pruebaEval(String exprStr) {
        Pantalla.setText("Thinking...");
        try {
            CalculadoraControlador calculadora = new CalculadoraControlador(exprStr);
            if(!calculadora.revisaParentesis()) {
                Pantalla.setText("  Check Parenthesis");
            }
            else {
                if(!calculadora.revisaOperadores()) {
                    Pantalla.setText("   Check Operators");
                }
                else {
                    calculadora.calculaResultado();
                    Pantalla.setText("" + calculadora.getResultado());
                    expreStr = "" + calculadora.getResultado();
                }
            }
        } catch (Exception e) {
            Pantalla.setText("    Check input");
        }
    }

}








